name: DORA Metrics

on:
  push:
    branches:
      - main

jobs:
  track-dora:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Lead Time
        run: |
          COMMIT_TIME=$(git log -1 --format=%ct)
          CURRENT_TIME=$(date +%s)
          LEAD_TIME=$(( (CURRENT_TIME - COMMIT_TIME) / 60 ))
          echo "LEAD_TIME=$LEAD_TIME" >> $GITHUB_ENV

      - name: Log Deployment to Google Sheets
        run: |
          curl -X POST "https://script.google.com/macros/s/AKfycbzrNJehEgy_7ByPDlje2gdSCfz37Jt5ls6uxEpz2hXngCtpLMmxyKX7J4gyanghFoN2/exec" \
               -H "Content-Type: application/json" \
               -d '{
                     "repository": "${{ github.repository }}",
                     "status": "Success",
                     "lead_time": "${{ env.LEAD_TIME }}",
                     "failure_rate": "5%", 
                     "mttr": "10"
                   }'
